
"""Add Red Door Models

Revision ID: b1509218f14e
Revises: 
Create Date: 2026-03-08 18:12:38.495226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1509218f14e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('items_title_idx'), 'items', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('segment_groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pdpa_consent', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('nfc_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tier_at_issue', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tap_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tap_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('nfc_cards_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nfc_cards_pkey'))
    )
    op.create_index(op.f('nfc_cards_card_id_idx'), 'nfc_cards', ['card_id'], unique=True)
    op.create_index(op.f('nfc_cards_member_id_idx'), 'nfc_cards', ['member_id'], unique=False)
    op.create_table('tap_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('tap_type', sa.String(length=50), nullable=False),
    sa.Column('reader_id', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['nfc_cards.card_id'], name=op.f('tap_events_card_id_fkey')),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('tap_events_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tap_events_pkey'))
    )
    op.create_index(op.f('tap_events_card_id_idx'), 'tap_events', ['card_id'], unique=False)
    op.create_index(op.f('tap_events_member_id_idx'), 'tap_events', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tap_events_member_id_idx'), table_name='tap_events')
    op.drop_index(op.f('tap_events_card_id_idx'), table_name='tap_events')
    op.drop_table('tap_events')
    op.drop_index(op.f('nfc_cards_member_id_idx'), table_name='nfc_cards')
    op.drop_index(op.f('nfc_cards_card_id_idx'), table_name='nfc_cards')
    op.drop_table('nfc_cards')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('items_title_idx'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
