
"""add_events_connections_service_requests

Revision ID: 53f5f15ada8c
Revises: b1509218f14e
Create Date: 2026-03-08 19:17:50.152244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53f5f15ada8c'
down_revision: Union[str, None] = 'b1509218f14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('target_segments', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('min_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('events_title_idx'), 'events', ['title'], unique=False)
    op.create_table('event_rsvps',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('rsvp_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_rsvps_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('event_rsvps_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'member_id', name=op.f('event_rsvps_pkey'))
    )
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('member_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('service_requests_assigned_to_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('service_requests_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('service_requests_pkey'))
    )
    op.create_index(op.f('service_requests_member_id_idx'), 'service_requests', ['member_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_a_id', sa.UUID(), nullable=False),
    sa.Column('member_b_id', sa.UUID(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('tap_event_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_a_id'], ['users.id'], name=op.f('connections_member_a_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_b_id'], ['users.id'], name=op.f('connections_member_b_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tap_event_id'], ['tap_events.id'], name=op.f('connections_tap_event_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('connections_pkey'))
    )
    op.create_index(op.f('connections_member_a_id_idx'), 'connections', ['member_a_id'], unique=False)
    op.create_index(op.f('connections_member_b_id_idx'), 'connections', ['member_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('connections_member_b_id_idx'), table_name='connections')
    op.drop_index(op.f('connections_member_a_id_idx'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('service_requests_member_id_idx'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_table('event_rsvps')
    op.drop_index(op.f('events_title_idx'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
