
"""add_staff_notes_to_users

Revision ID: f7621a6fc054
Revises: 79785d652e7d
Create Date: 2026-03-09 03:58:28.029744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7621a6fc054'
down_revision: Union[str, None] = '79785d652e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'staff_notes')
    # ### end Alembic commands ###
