
"""add_lockers_tabs_tab_items

Revision ID: 79785d652e7d
Revises: 53f5f15ada8c
Create Date: 2026-03-08 22:34:13.435699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79785d652e7d'
down_revision: Union[str, None] = '53f5f15ada8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lockers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('locker_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_member_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_member_id'], ['users.id'], name=op.f('lockers_assigned_member_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('lockers_pkey'))
    )
    op.create_index(op.f('lockers_assigned_member_id_idx'), 'lockers', ['assigned_member_id'], unique=False)
    op.create_index(op.f('lockers_locker_number_idx'), 'lockers', ['locker_number'], unique=True)
    op.create_table('tabs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('tabs_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tabs_pkey'))
    )
    op.create_index(op.f('tabs_member_id_idx'), 'tabs', ['member_id'], unique=False)
    op.create_table('tab_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tab_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tap_event_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], name=op.f('tab_items_tab_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tap_event_id'], ['tap_events.id'], name=op.f('tab_items_tap_event_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('tab_items_pkey'))
    )
    op.create_index(op.f('tab_items_tab_id_idx'), 'tab_items', ['tab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tab_items_tab_id_idx'), table_name='tab_items')
    op.drop_table('tab_items')
    op.drop_index(op.f('tabs_member_id_idx'), table_name='tabs')
    op.drop_table('tabs')
    op.drop_index(op.f('lockers_locker_number_idx'), table_name='lockers')
    op.drop_index(op.f('lockers_assigned_member_id_idx'), table_name='lockers')
    op.drop_table('lockers')
    # ### end Alembic commands ###
